module.exports = [
    {
        ignores: [
            'node_modules/**',
            'test-results/**',
            'playwright-report/**',
            '**/*.min.js',
            'coverage/**',
            '.husky/**',
            '.vscode/**',
            'debug-operacao.js',
            'universal_webapp_stack_com_guia/**',
            'src/business/TradingStrategy.js',
            'auto-execucao-timeline.js',
            'preventive-testing-system.js',
            'tests/system-health-validator.js',
        ],
    },
    {
        languageOptions: {
            ecmaVersion: 2021,
            sourceType: 'module',
            globals: {
                // Browser globals
                window: 'readonly',
                document: 'readonly',
                console: 'readonly',
                setTimeout: 'readonly',
                setInterval: 'readonly',
                clearTimeout: 'readonly',
                clearInterval: 'readonly',
                requestAnimationFrame: 'readonly',
                performance: 'readonly',
                localStorage: 'readonly',
                navigator: 'readonly',
                location: 'readonly',
                alert: 'readonly',
                fetch: 'readonly',
                URL: 'readonly',
                Blob: 'readonly',
                getComputedStyle: 'readonly',
                MutationObserver: 'readonly',
                CustomEvent: 'readonly',
                Event: 'readonly',
                Audio: 'readonly',
                FileReader: 'readonly',
                Element: 'readonly',
                Node: 'readonly',
                indexedDB: 'readonly',

                // Node.js globals
                require: 'readonly',
                module: 'readonly',
                process: 'readonly',
                __dirname: 'readonly',

                // External libraries
                Chart: 'readonly',

                // Project globals
                state: 'writable',
                config: 'writable',
                ui: 'writable',
                logic: 'writable',
                charts: 'writable',
                dom: 'writable',
                Features: 'readonly',
                events: 'readonly',

                // Additional browser globals
                confirm: 'readonly',
                btoa: 'readonly',
                atob: 'readonly',
                PerformanceObserver: 'readonly',
                Headers: 'readonly',
                cancelAnimationFrame: 'readonly',
                Notification: 'readonly',
                html2canvas: 'readonly',
                arguments: 'readonly',
                IntersectionObserver: 'readonly',
                screen: 'readonly',
                sessionStorage: 'readonly',
                URLSearchParams: 'readonly',
                AbortSignal: 'readonly',

                // Project specific globals
                TradingOperationsManager: 'readonly',
                winRate: 'readonly',
                lossRate: 'readonly',
                detective: 'readonly',
                context: 'readonly',
                testDOMMapping: 'readonly',
                cssResolver: 'readonly',
                testUIComponents: 'readonly',
                testLogicFunctions: 'readonly',
                testSidebar: 'readonly',
                testInitialization: 'readonly',
                runQuickTests: 'readonly',
                dbManager: 'readonly',
                uiServicesFacade: 'readonly',
                SafeProtectionSystem: 'readonly',
                mapDOM: 'readonly',
                sanitizeSessionData: 'readonly',
                testSystem: 'readonly',
                testRunner: 'readonly',
                TestRunner: 'readonly',
                validation: 'readonly',
                UICommandFactory: 'readonly',
                globalCommandInvoker: 'readonly',
                globalDocGenerator: 'readonly',
                globalAutoDocumenter: 'readonly',
                globalPredictiveAnalyzer: 'readonly',
                globalAutoPreventionSystem: 'readonly',
            },
        },
        rules: {
            'no-undef': 'error',
            'no-unused-vars': 'off',
            'no-console': 'off',
            'no-eval': 'warn',
        },
    },
];
